### ISSUE TITLE
Stopped sending entries to channels

### ISSUE THREAD

**Issue by rossnomann** [rossnomann/telefeed#2]
Possibly due to ServerDisconnectedError
```
future: <Task finished coro=<Bot.loop() done, defined at /usr/local/lib/python3.6/site-packages/aiotg/bot.py:110> exception=ServerDisconnectedError(None,)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiotg/bot.py", line 129, in loop
    timeout=self.api_timeout
  File "/usr/local/lib/python3.6/site-packages/aiotg/bot.py", line 378, in _api_call
    response = await self.session.post(url, data=params, proxy=self.proxy)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 748, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

**Comment by rossnomann** [comment]
Closed in 4c8f1e543f8e3d1a98bf430036283357a8519870
